[package]
name = "rogrep-index"
description = "rogrep index"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rogrep-model.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
